version: '3.1'
services:
  db:
    image: postgres:12-alpine
    environment:
      POSTGRES_PASSWORD: pwd
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports: 
      - 5432:5432
      